<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * 
 * @return [type] [description]
 */
function panopoly_news_demo_menu(){
  $items['admin/content/remove-demo-content/panopoly-news'] = array(
    'title' => 'Remove Panopoly News demo content',
    'page callback' => 'panopoly_news_demo_disable_demo',
    'page arguments' => array('admin/content'),
    'access arguments' => array('administer features'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['news/remove-demo-content/panopoly-news'] = array(
    'title' => 'Remove Panopoly News demo content',
    'page callback' => 'panopoly_news_demo_disable_demo',
    'page arguments' => array('news'),
    'access arguments' => array('administer features'),
    'type' => MENU_LOCAL_ACTION,
  );

  return $items;
}

function panopoly_news_demo_disable_demo($redirect_path){
	//Disable the module (and thus the content)
	module_disable(array('panopoly_news_demo'));

	//Clear the menu cache
	menu_rebuild();

	//Set an informative message
	drupal_set_message(t('The Panopoly News demo content has been disabled.'));

	//Reload the admin content page
	drupal_goto($redirect_path);
}

/**
 * Delete all (node) defaultcontent in $feature_name.
 *
 * @todo: THIS FUNCTION IS UNUSED. Delete before going live.
 * 
 * @return [type] [description]
 */
function panopoly_news_demo_delete_defaultcontent($feature_name){
	if(module_load_include('inc', $feature_name, $feature_name . '.features.content')){
		//Load all the featurized pieces of defaultcontent
		$content_defaults_function = $feature_name . '_content_defaults';
	  $components = $content_defaults_function();
	  usort($components, 'defaultcontent_import_sort');

	  //Delete all the defaultcontent
	  if (!empty($components)) {
	    foreach ($components as $component) {
	      if ($nid = defaultcontent_get_default($component->machine_name)) {
	        $node = node_delete($nid);
	      }
	    }
	  }
	}
}